In [2]:
import numpy as np
lista = [1,2,3,4]
arr = np.array(lista)
print(arr)
arr

[1 2 3 4]


array([1, 2, 3, 4])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(5)*3 # Array de numeros 1 multiplicados por 3 obtendo array de numeros 3

array([3., 3., 3., 3., 3.])

In [12]:
np.arange(2.5,11.5,1.5) # Array começando em 2.5 e indo até 11.5 com passo 1.5

array([ 2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [13]:
np.linspace(1,2,30) # Array de 30 posições que vai de 1 até 2, o passo é automaticamente definido

array([1.        , 1.03448276, 1.06896552, 1.10344828, 1.13793103,
       1.17241379, 1.20689655, 1.24137931, 1.27586207, 1.31034483,
       1.34482759, 1.37931034, 1.4137931 , 1.44827586, 1.48275862,
       1.51724138, 1.55172414, 1.5862069 , 1.62068966, 1.65517241,
       1.68965517, 1.72413793, 1.75862069, 1.79310345, 1.82758621,
       1.86206897, 1.89655172, 1.93103448, 1.96551724, 2.        ])

In [16]:
np.random.seed(42) # É possível fixar a aleatoriedade para obter os mesmo valores sempre usando metoo seed
np.random.rand(5) # gera array com valores entre 0 e 1 com numero de posições especificado

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [17]:
np.random.randint(5,10,6) # 6 numeros aleatórios entre 5 e 10

array([7, 7, 7, 9, 8, 7])

In [19]:
np.random.choice(np.arange(10,101),20,replace=False) # 20 Numeros aleatórios de 10 a 100 sem reposição(não repete)

array([55, 59, 86, 63, 89, 27, 25, 28, 26, 19, 88, 33, 76, 75, 30, 40, 99,
       79, 91, 78])

In [20]:
np.random.normal(0,1,20) # 20 numeros gerados com média  igual a 0 e desvio padrão igual a 1

array([-0.0185508 , -1.67350462, -1.07253183, -0.99258618,  0.10234768,
       -0.43260928, -0.6591823 ,  0.0039373 ,  0.4777541 , -0.25902864,
       -0.57470921, -0.42149822,  0.33982096, -0.00738015,  0.76729684,
       -1.14979258, -0.77533611,  0.77314086, -0.80182784,  1.38401572])

In [25]:
# Gerando 2 arrays para realizar algumas operações

array1 = np.random.randint(5,10,5) 
array2 = np.linspace(1,10,5)

In [33]:
# Converter array em lista
array1.tolist()

[8, 7, 8, 7, 6]

In [26]:
array1


array([8, 7, 8, 7, 6])

In [27]:
array2

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
# fazendo slices
array2[2::2]

array([ 5.5, 10. ])

In [32]:
# Multiplicando arrays
print(array2*array1)
print(array1+5)
print(array2/7)
print((array2/array1)**2)

[ 8.   22.75 44.   54.25 60.  ]
[13 12 13 12 11]
[0.14285714 0.46428571 0.78571429 1.10714286 1.42857143]
[0.015625   0.21556122 0.47265625 1.22576531 2.77777778]


## Métodos


In [35]:
array_testes = np.arange(1,20,3.5)

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5])

In [37]:
array_testes.max() # Maior valor

18.5

In [38]:
array_testes.argmax() # Posição do maior valor

5

In [39]:
# Menor Valor
array_testes.min()

1.0

In [40]:
# Posição do menor valor
array_testes.argmin()

0

In [41]:
# Média
array_testes.mean()

9.75

In [42]:
# Soma
array_testes.sum()

58.5

In [43]:
# Devio padrão
array_testes.std()

5.977387946809766

In [46]:
# Tamanho
len(array_testes) 
# ou
array_testes.shape[0] # Atributo shape diz o tamanho de cada dimensão doa array em uma tupla

6

In [48]:
# Mudar tipo de dados do array
print(array_testes.dtype) # Verificando tipo
array_testes.astype(int) # Mudando para o que queremos

float64


array([ 1,  4,  8, 11, 15, 18])

In [51]:
# Criando matriz array por meio de lista de listas
matriz = [  [1,2,3],
            [1,2,3]  ]
matriz_arr = np.array(matriz)
matriz_arr

array([[1, 2, 3],
       [1, 2, 3]])

In [69]:
# Criando multidimensional a partir de array unidimensional
arr = np.arange(1,27,3) # Criando array de 10 posições
matriz2 = arr.reshape((3,3)) # Reordenando em matriz 3x3

In [83]:
matriz2 [:,0]# Pegando o primeiro valor de cada linha. para usar slices usamos , e dentro de um [] só
# ordem normal, linha-coluna

array([ 1, 10, 19])

In [84]:
# Criar Matriz identidade
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
np.random.randint(1,101,[5,2]) # Matriz aleatoria entre 1 e 100 no formato 5x2 passando lista no argumento size

array([[67, 19],
       [20, 96],
       [71, 52],
       [33, 40],
       [39, 82]])

In [87]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Máscaras e Filtros


In [93]:
matriz2 > 10 # Verificando se os valores são maiores q 10

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [95]:
matriz2[matriz2>10] # Retorna somente elementos onde a expressão > 10 é verdade

array([13, 16, 19, 22, 25])

In [97]:
matriz2[matriz2%2==0 ]# Pares

array([ 4, 10, 16, 22])

In [102]:
matriz2[(matriz2%2==0) & (matriz2 > 10)] # Valores maiores q 10 e pares

array([16, 22])

In [103]:
matriz2[(matriz2 > 10)|(matriz2%2!=0)] # ímpares ou maiores que 10

array([ 1,  7, 13, 16, 19, 22, 25])

In [105]:
np.repeat(42,7) # repete 42 7 vezes

array([42, 42, 42, 42, 42, 42, 42])